# Change these first
owner: CityOfDetroit # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: City of Detroit
    url: https://detroitmi.gov
  - name: The Neighborhoods
    url: https://theneighborhoods.org
  - name: Arts, Culture, and Entrepreneurship
    url: https://ace.detroitmi.gov
  - name: Detroit at Work
    url: https://detroitatwork.com
  - name: Grow Detroit's Young Talent
    url: https://gdyt.org
  - name: Green Stormwater Infrastructure
    url: https://detroitstormwater.org
  - name: Detroit's Playbook
    url: https://playbook.detroitmi.gov

status-website:
  baseUrl: /uptime
  name: City of Detroit Uptime
  introTitle: "**City of Detroit Uptime** is the open-source uptime monitor and status page for websites managed by the City of Detroit."
  introMessage: View the live status, active incidents, and historic uptime for websites managed by the City of Detroit below. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
